on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        touch my.jar
        mvn deploy:deploy-file -DgroupId=group-id \
          -DartifactId=artifact-id \
          -Dversion=1.0 \
          -Dpackaging=jar \
          -Dfile=my.jar \
          -DrepositoryId=github \
          -Durl=https://maven.pkg.github.com/${{ github.repository }}
